[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
confidential_transfer_arcium_demo = "75MYEEgbXuUeXwUa834fhyAWgEtsjrajgWjiQj5Th3eF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/home/lemon/Codingstuff/confidential-transfer-arcium-demo/artifacts/arcium_program_0.1.47.so"
